### ISSUE TITLE
Latest changes aren't reflected on webpage

### ISSUE THREAD

**Issue by scowalt** [cs-education/sysassets#7]
At time of writing, the files in the `transcriptions` folder are not available on the sysassets site. For example, [reverse_index.json should be available here](http://cs-education.github.io/sysassets/transcriptions/reverse_index.json). However, files from previous commits are still available. Is this a bug in gh-pages? Seems like our latest changes got committed but not deployed.

**Comment by angrave** [comment]
It might be a bug in gh_pages because transcriptions/ was created using a merge-pull after we moved the repo to a new org?

You could try creating new test file in / and new file in transcriptions/  git add+push remote. Wait 1hr and see if they are published (and if this leads to transcriptions/ being published)

Bit more heavy handed: Try git mv transcriptions to trans1 ; git add+push remote; git mv back to transcriptions; add+ push ; maybe that will be enough to tickle it into publishing it.

**Comment by scowalt** [comment]
@neelabhg knows much more about this issue than I do. One possible problem is that our repo could be too large for Github to want to publish. [This article](https://help.github.com/articles/what-is-my-disk-quota/) has a bit more information. Ultimately, if we discover that this may consistently be an issue, we may need to re-evaluate using Github pages as our hosting platform for this repository.

For now, I agree that we could try doing some more direct changes to the repository to see if it will "trigger" a publish to take place.

**Comment by neelabhg** [comment]
I told @jdtran23 and @scowalt about this earlier. The latest page build failed. I received an email about this asking to check the [troubleshooting page](https://help.github.com/articles/troubleshooting-github-pages-build-failures/), and even the repo's settings page shows this:

![image](https://cloud.githubusercontent.com/assets/846827/6967340/49a90f06-d924-11e4-9da0-c160efd7f713.png)

There is no specific error message. I suspect this might be because of the size of the repository.

In any case, it might be worthwhile to trigger a build again. I'll try that now by pushing to master.

**Comment by angrave** [comment]
How big is your .git folder?
e.g. Maybe some old (deleted) videos in the archive have pushed it over 
the limit.

NB There are ways to trash the history but they are somewhat arcane 
dangerous (e.g. might accidentally all files from repo)

IMHO simpler + much safer to drop all history - just start with a blank 
slate and make a new experiemtnal repo :

Make a new repo 'sysassets2', drop the master branch, create the 
gh-pages branch and copy everything in.

L.

**Comment by neelabhg** [comment]
Update: I pushed a trivial change to trigger a build, and it succeeded. The transcriptions are live.
